# Generated by Django 4.2.3 on 2023-07-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=5)),
                ('publication', models.CharField(max_length=40)),
                ('genre', models.CharField(default=None, max_length=60)),
            ],
        ),
    ]
